### ISSUE TITLE
Unable to cancel Delivered LocalNotifications using id

### ISSUE THREAD

**Issue by codemeall** [zo0r/react-native-push-notification#1018]
I am unable to cancel Delivered localnotification with their ID.

**Comment by Linoa65** [comment]
I think there is a true problem with this feature. Many issues are open, and people says that it don't works, after it works, after it don't works ... For now I think the feature is broken, I tried different parameters to send to this module to cancel local notification, but nothing seems to work? We cannot handle properly the management of notification in our app on android side because of this.

Please, someone confirm that the feature is broken, or give a true solution with explanation, or a link, but not just a "Heyyy it works ty nice !".

Thanks.

**Comment by ignasbol** [comment]
@Linoa65 can confirm that removing `tag` from notification details allows notification to be cancelled with `cancelLocalNotifications`

**Comment by athondapu** [comment]
Hi All,

After a one day struggle I found the way to delete the delivered notification by ID. Here is how I solved my problem.

```    PushNotification.clearLocalNotification(parseInt(id, 10));```

Please let me know if I am making any mistake.

**Comment by disappearer** [comment]
@athondapu Thank you, that worked for me 🙂 Although, typescript compiler is complaining and this method isn't mentioned anywhere in the docs.

**Comment by Unforgiven-wanda** [comment]
@athondapu This did not work for me
I have read elswhere that removing the tag attribute from localnotification was also an issue, but neither solutions worked.
Could I please trouble you to share a full example? Thank you.

**Comment by AntonOmelchuk** [comment]
I have a problem with deleting delivered notifications, cancel Local Notification doesn't work, I tried all solutions that I read

**Comment by winardis** [comment]
Hi i'm also having the issue of removing delivered notifications i checked the documentation it seems only IOS has the function to remove delivered notification via `PushNotificationIOS.getDeliveredNotifications(callback);` 
but what about the android's removal on delivered notifications

**Comment by Dallas62** [comment]
Hi @willnaoosmit 
Check that:
https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L420

**Comment by winardis** [comment]
> Hi @willnaoosmit
> Check that:
> https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L420

Hi i checked on the documentation, the function of clearLocalNotification() is used to cancel operations not removing delivered notifications. Because i have tried using the function it works for canceling scheduled notifications, but not on removing delivered notifications

`
    PushNotification.cancelLocalNotifications({ id: scheduledNotificationId });
    PushNotification.cancelLocalNotifications({ id: `${scheduledNotificationId}` });
`

1) cancelLocalNotifications
The id parameter for PushNotification.localNotification is required for this operation. The id supplied will then be used for the cancel operation.

https://github.com/zo0r/react-native-push-notification#1-cancellocalnotifications

**Comment by winardis** [comment]
> Hi @willnaoosmit
> Check that:
> https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L420

Hi i checked on the documentation, the function of clearLocalNotification() is used to cancel operations not removing delivered notifications. Because i have tried using the function it works for canceling scheduled notifications, but not on removing delivered notifications

`PushNotification.cancelLocalNotifications({ id: scheduledNotificationId });`

cancelLocalNotifications
The id parameter for PushNotification.localNotification is required for this operation. The id supplied will then be used for the cancel operation.
https://github.com/zo0r/react-native-push-notification#1-cancellocalnotifications

**Comment by pdooo** [comment]
> I have a problem with deleting delivered notifications, cancel Local Notification doesn't work, I tried all solutions that I read

Same. 
The only thing that kind of helped me was [this](https://github.com/zo0r/react-native-push-notification/issues/1296#issuecomment-593557272). For some reason after adding `repeatType` in `PushNotification.localNotification` I could remove already delivered notifications sitting in my notifications center. Problem is that I don't want to use `repeatType` because I just want to remove my regular local notifications. 

Here version working with repeatType:

```
PushNotification.localNotification({
        id: id,
        actions: ['Copy', 'Remove'],
        repeatType: 'week',
        invokeApp: false,
        autoCancel: false,
        largeIcon: "ic_launcher",
        smallIcon: "ic_notification",
        channelId: "localNoti",
        title: title, 
        message: url, 
        ongoing: IsOnGoing, 
});
```
```
PushNotification.configure({
    onNotification: function (notification) {
      var link = notification.message;
      PushNotification.cancelLocalNotifications({ id: notification.id; });
    },
    onAction: function (notification) {
      if (notification.action == 'Remove'){
        PushNotification.cancelLocalNotifications({ id: notiID });
        console.log(notiID)
      }
  },
  popInitialNotification: true,
  requestPermissions: Platform.OS === 'ios',
  
})
```

**As soon as I remove `repeatType: 'week'` from `PushNotification.localNotification` it stops working**
