### ISSUE TITLE
With Do Not Disturb On, Still Making Sound on Android

### ISSUE THREAD

**Issue by bellindj** [zo0r/react-native-push-notification#1053]
I am using 3.1.2 in my application. On iOS, all works fine. On Android, my notifications are still making a sound when I have DND turned on. Pixel 3 on Android Pie (9).

When I setup my push notification, I am using the settings below. Based on the priority and importance being set to "default", I don't think the notifications should still make sounds. All my other apps respect DND and their notifications are silent.

On RN 0.57.7.

```
  notificationObject = {
    title: title,
    message: message, // (required)
    playSound: true, // (optional) default: true
    soundName: "default", 
    number: "10", 
    // actions: '[""]', 
    date: date
  };

  if (Platform.OS === "ios") {
    PushNotification.localNotificationSchedule(
      Object.assign(notificationObject, {
        alertAction: "view",
        userInfo: { id: id }
      })
    );
  } else {
    PushNotification.localNotificationSchedule(
      Object.assign(notificationObject, {
        id: id, 
        autoCancel: true,
        largeIcon: "ic_launcher_round", 
        vibrate: true,
        vibration: 300,
        ongoing: false, 
        priority: "default",
        visibility: "public", 
        importance: "default" 
      })
    );
  }
```

**Comment by hubermat** [comment]
Same problem for me on Huawei P20 Lite (Android 9.0)

**Comment by hubermat** [comment]
Problem still exists with react-native-push-notification 3.4.0

**Comment by Dallas62** [comment]
Hi @hubermat 
Did you set the importance to `default` ?

**Comment by hubermat** [comment]
I use 
```
priority: 'high', // (optional) set notification priority, default: high
visibility: 'private', // (optional) set notification visibility, default: private
importance: 'high', // (optional) set notification importance, default: high
```

**Comment by Dallas62** [comment]
You can try `default` importance, this should make the expected behaviour:
https://developer.android.com/training/notify-user/channels#importance

**Comment by hubermat** [comment]
No, even with importance = 'default', the behaviour with 3.4.0#dev (current #dev) is like this:
If do-not-disturb is activated on the device (Samsung M30s, Android 9), the local notification is shown in the status bar (no heads-up notification due to importance=default, that's okay), BUT: the device vibrates and the default system sound plays! This should not be the case, if do-not-disturb is active!

**Comment by Dallas62** [comment]
This is really strange since there is no specific code to force the notification. I found that some versions might have a bug with DND, but it should not occur on Android 9.

**Comment by Dallas62** [comment]
Hi @hubermat @bellindj 
Do you have any specific parameters in DND ?
Like allowing contact, calls, messages, ... ?

**Comment by wmonecke** [comment]
Hi @Dallas62!

Thank you for your amazing work :) I am also experiencing the issue, many users have reported sound and vibration even with DND.

I am using: 

````
priority: 'high', // (optional) set notification priority, default: high
visibility: 'public', // (optional) set notification visibility, default: private
importance: 'high', // (optional) set notification importance, default: hig
`````

**Comment by Dallas62** [comment]
Hi @wmonecke 
I think this error has been fixed but only for new installation.
The problem was the sound was typed as ALARM, so it’s played even with DND. This is stick to the channel, once it’s created... 🤷‍♂️ you need to remove them.

In the version on `dev` branch that I will release this weekend, there is a more complete channel management that will allow you to choose channel_id and list/remove them.

**Comment by wmonecke** [comment]
Sounds awesome!

Thank you so much :)

All the best and stay safe,

Walter Monecke
software engineer @ urban hero
