### ISSUE TITLE
Notification doesn't fire App is in foreground android ?

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [zo0r/react-native-push-notification#1061]
Hi,

I have integrate remote notification in my react native app. When App is killed and background the notification is coming on notification center and working fine, but when app is in foreground there is nothing happen. No one method is called,

I have do the below code for notification. The issue is only in android, iOS working fine.

Code : 

```
export function setupPushNotification(handleNotification) {
  PushNotification.configure({
    // (optional) Called when Token is generated (iOS and Android)
    // smallIcon: "ic_notification",
    onRegister: function (token) {
      console.log('TOKEN:', token.token);
      AsyncStorage.setItem('deviceToken', token.token);
      //setStoredData('deviceToken', token.token)
      PushNotification.popInitialNotification((notification) => {
        if (notification) {
          console.log('** NOTIFICATION:', notification);
          handleNotification(notification);
        }
      });
    },
    // (required) Called when a remote or local notification is opened or received
    onNotification: function (notification) {

      console.log('** NOTIFICATION: **', notification);

      if (Platform.OS === 'ios') {
        if (notification.alert.length !== 0) {
          handleNotification(notification)
          notification.finish(PushNotificationIOS.FetchResult.NoData);
        }
      } else {
        handleNotification(notification)
      }

    },
    // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications) 
    senderID: "303349031154",
    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
      alert: true,
      badge: true,
      sound: true
    },
    popInitialNotification: false,
    requestPermissions: true,
  });

  return PushNotification
}

```

**Comment by tmaly1980** [comment]
SAME HERE! The notification works when the app is in the background, but onNotification never is called when the app is open. Any luck?

**Comment by tmaly1980** [comment]
I just resolved this by fixing the AndroidManifest.xml to what's in the README. I was migrating from GCM to FCM and missed a few lines:

```
        <service      android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
                android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

**Comment by joaom182** [comment]
Same issue here.

@tmaly1980 i've tried you workarround, but not works.

**Comment by jacek213** [comment]
For me `localNotification` is never sent. Filled up everything according to README.

**Comment by tmaly1980** [comment]
@joaom182 If you follow that link, there are a lot of other things to that could be missing. You'll have to follow the instructions carefully. What I did to fix it was just one part I overlooked or didn't think was important. I was wrong.

**Comment by jimerino** [comment]
I've just answer to another question:

Android has 2 kind of notifications: silent and noisy.

The "noisy ones" only call onNotification when App is foreground but not in background
The "silent ones" call onNotification even when App is in background

The only difference between them is that the silent ones only has the "data" section and doesn't have the "notification" section.

https://firebase.google.com/docs/cloud-messaging/concept-options

The solution I've made is modify the service to launch the 2 notifications. The silent one to trigger onNotif in every circumstances and the noisy one to show the notification in the notification center and make a sound.

But beware because if the app is in foreground, onNotification is called twice (for the silent and another for the noisy notification).

Regards
