### ISSUE TITLE
Token generated but couldn't receive notificatios sent from fcm in iOS only

### ISSUE THREAD

**Issue by aryalprakash** [zo0r/react-native-push-notification#1062]
I've set up all the instructions mentioned on this package and PushNotificationIOS by react native. https://facebook.github.io/react-native/docs/pushnotificationios.html

`onRegister` gets called and token is generated successfully but I couldn't get any notifications on my iPhone sent from firebase.

It's working fine on Android.

**Comment by justmesam** [comment]
@aryalprakash  any progress on this issue??

**Comment by dophlin** [comment]
+1

**Comment by ankitgaurish** [comment]
+1

**Comment by justmesam** [comment]
I figured out what was happening, when your `onregister` gets called it generates a device token and not an FCM token for iOS but generates FCM token for Android. So that's why you could receive notifications on Android and not iOS since Firebase sends notifications using the devices FCM token but not the device token.

What I did was set Firebase for iOS following [this](https://firebase.google.com/docs/cloud-messaging/ios/client?authuser=0). And then I created a RN bridge that sends the FCM token received from the Firebase setup to the front-end, I accessed it using NativeModules and then I could get the FCM token to the servers and everything works fine.

**Comment by AndreyPatseiko** [comment]
@justmesam You right. Can you share IOS code. I don't know Objective-C.
