### ISSUE TITLE
Force closes on load?

### ISSUE THREAD

**Issue by KemikalGeneral** [zo0r/react-native-push-notification#1066]
Hi,

I'm trying out this package and followed the setup guide, but the app opens on load, and closes straight away, with no errors.

I'm not having any other issues with my app, only when i include this package. 

Any idea what might be causing this?

Thanks xxx

**Comment by michelepapale1996** [comment]
Hi,
I'm having your same problems. Until yesterday, everything was fine. From today, the app doesn't open anymore. If I run the app, however, from a real mobile phone, this is the exception it throws: 
![photo_2019-05-07_20-06-19](https://user-images.githubusercontent.com/9197981/57322463-db52fb80-7103-11e9-831e-f4dde8270f56.jpg)

I'm sure that the problem is caused by react-native-push-notification because if i remove this one, the app works.

**Comment by michelepapale1996** [comment]
https://github.com/invertase/react-native-firebase/issues/2122#issuecomment-490467564 this, worked for me!
