### ISSUE TITLE
incompatible types: RNPushNotificationListenerServiceGcm cannot be converted to Context

### ISSUE THREAD

**Issue by Frank-vdm** [zo0r/react-native-push-notification#1074]
node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotificationListenerServiceGcm.java:51: error: incompatible types: RNPushNotificationListenerServiceGcm cannot be converted to Context
                ApplicationBadgeHelper.INSTANCE.setApplicationIconBadgeNumber(this, badge);

my I doing something wrong or what? I've linked the module and added the manifest config, but then i try to buid android i get this error

**Comment by Kuhne1** [comment]
I also have this, did you manage to solve it?

**Comment by Kuhne1** [comment]
So I think I have the solution, It got rid of the error at least and allowed me to build. 
I updated my build.gradle project wide property settings.
Updated googlePlayServicesVersion from 11.0.0 to
 googlePlayServicesVersion = "15.0.1"
This got rid of the error for me. You may want to check out https://github.com/zo0r/react-native-push-notification/issues/1098 as well because there is a new issue with Google releasing a breaking change for this library with GCM.

This is my full ext for your reference
 ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "15.0.1"
    }
Hope this helps :)

**Comment by AndresMaca** [comment]
Hi @Kuhne1 Could you post the dependencies chunk in android/build.gradle and in android/app/build.gradle , we're facing the same issue

**Comment by Kuhne1** [comment]
Okay, So I'll just run you basically through what I did to fix it because It was a combination of different threads on this page + stack overflow. I'll preface this with I'm not an expert in android studio and I more came to this fix by bruteforcing trying all the different threads I found out there till it worked. 

android/app/build.gradle

//I had to add in multiDex after I fixed the context issue, to resolve the error that appeared afterwards, you may not need it. 
defaultConfig {
   ….
    multiDexEnabled true
…. 
}


dependencies {

    compile project(':react-native-push-notification')
    implementation fileTree(dir: "libs", include: ["*.jar"])

//These could be the lines that you need to add
    implementation(project(":react-native-push-notification"),  {
        exclude group: "com.google.android.gms"
    })
    implementation "com.google.android.gms:play-services-gcm:17.0.0"
    implementation 'com.android.support:multidex:1.0.3' 

//End of lines you need to add
    implementation "com.facebook.react:react-native:+"  
}
//I got this from another stack overflow thread and it resolves the manifest problem you may have afterwards.
configurations.all {
    resolutionStrategy {
        force 'com.google.android.gms:play-services-gcm:16.1.0'
        force 'com.google.android.gms:play-services-base:16.1.0'
        force 'com.google.firebase:firebase-core:16.0.6'
        force 'com.google.firebase:firebase-messaging:17.6.0'
    }}
//End Manifest Fix
////////////////Android/build.gradle ////////////////////////////
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "15.0.1"
    }

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        
    }
}
 wrapper {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}


//////////////build.gradle Module: React-native-push-notifications////
So basically the issue to my understanding is that Google made a breaking change to it's GCM implementation. The push notifications library in their gradle uses '+' to use the latest version of the google play services. So you need to change that to my below code, to set your version so you're not affected by the latest breaking changes. 

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation "com.android.support:appcompat-v7:${safeExtGet('supportLibVersion', '28.0.0')}"
    implementation "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"
    implementation "com.google.android.gms:play-services-gcm:${safeExtGet('googlePlayServicesVersion', '16.1.0')}"
    implementation 'me.leolin:ShortcutBadger:1.1.8@aar'
    implementation "com.google.firebase:firebase-messaging:${safeExtGet('firebaseVersion', '17.6.0')}"
}

**Comment by toonsend** [comment]
Thanks @Kuhne1.  I got it working with a  subset of your changes.

**android/build.gradle**
```
    ext {
      buildToolsVersion = "28.0.3"
      minSdkVersion = 16
      compileSdkVersion = 28
      targetSdkVersion = 28
      supportLibVersion = "28.0.0"
      googlePlayServicesVersion = "15.0.1"
    }

```

**android/app/build.gradle**
```
configurations.all {
  resolutionStrategy {
    force 'com.google.android.gms:play-services-gcm:16.1.0'
    force 'com.google.android.gms:play-services-base:16.1.0'
    force 'com.google.firebase:firebase-core:16.0.6'
    force 'com.google.firebase:firebase-messaging:17.6.0'
}}
```
