### ISSUE TITLE
RNCPushNotificationIOS.h file not found 

### ISSUE THREAD

**Issue by ydv0121** [zo0r/react-native-push-notification#1168]
React-native version - 0.58.4

installed react-native-push-notification

follow this steps of linking

Add the following to your Project: node_modules/@react-native-community/push-notification-ios/ios/PushNotificationIOS.xcodeproj
Add the following to Link Binary With Libraries: libRNCPushNotificationIOS.a

but xCode gives an error **RNCPushNotificationIOS.h file not found**  after cleaning the project and all stuff.

**Comment by Natkarock** [comment]
Hi! add `$(SRCROOT)/../node_modules/@react-native-community/push-notification-ios/ios` in your Header Search Path in Xcode.

**Comment by aaronpcz** [comment]
If you are using a Podfile you can also remove React-RCTPushNotification and add the following...

`pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'`

**Comment by RadagastCH** [comment]
Hi! try to run pod install in root iOS folder

**Comment by MoOx** [comment]
@Dallas62 I just faced this issue and I would have expected auto linking to handle this, am I wrong?

**Comment by Dallas62** [comment]
the iOS version is not a part of this library.

**Comment by MoOx** [comment]
I know that, but it's a dependency of this library https://github.com/zo0r/react-native-push-notification/blob/3d769ad2f661432dbeaed27f031ab13bd07985d4/package.json#L27
Maybe we should ask user to install themselves (& specify the version this package need in **peerDependencies** instead of *depdendencies* ?

**Comment by Madhu02** [comment]
Import the below two imports above the FB_SONARKIT_ENABLED in AppDelegate.m
#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>
#ifdef FB_SONARKIT_ENABLED //import above this line

This worked for me. Cheers

**Comment by shayelbaz1** [comment]
> Hi! try to run pod install in root iOS folder

I did the pos indtall in the ios folder while the Xcode is open and it Build Succeed for me. TNX!

**Comment by ilialezhnev** [comment]
> If you are using a Podfile you can also remove React-RCTPushNotification and add the following...
> 
> `pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'`
> 
> More details #1161

Works like a charm! Thanks!

**Comment by mianaamirshehzad** [comment]
Your project has issues with the paths (that arise due to incomplete installation of dependencies). 
Just clone the project again to somewhere else in your machine, run `pod install` in your `ios root folder` and you're good to go. That's how I fixed my issue. 

I faced this issue in my React Native project so I had to run npm install in my root directory before installing pods.
