### ISSUE TITLE
push notification not receiving from server or pushtry.com [IOS]

### ISSUE THREAD

**Issue by ishaq-aym** [zo0r/react-native-push-notification#1177]
i am unable to receive the notification on IOS from server or any other online fcm service but when i send the notification from firebase console then i received . i followed all the steps of integration of this library also generated APNS certificate . i dont know how to check the issue of this problem.

**Comment by melvinchng** [comment]
There is something that the documentation does not mention. For iOS, you are actually getting APN token instead of FCM token. What you have to do is manually convert/import from APN to FCM token. Took me days to figure this out, and here you go the [documentation](https://developers.google.com/instance-id/reference/server#create_registration_tokens_for_apns_tokens).

**Comment by agoel89** [comment]
I think [PushTry ](www.pushtry.com) have got more advanced version so that you can get to know if there is an issue with certificate or token. Make sure to check production flag if its production key. You might also need to enter bundle id for the same.
