### ISSUE TITLE
i´m not recieving any push notification, on my ios device? anyone had the same issue

### ISSUE THREAD

**Issue by saidkayed** [zo0r/react-native-push-notification#1206]
i got the device token, when i try to send a push notification msg from firebase, i get no notification on IOS. everything works fine on android

**Comment by huyvm** [comment]
check token device general pls

**Comment by HarshitMadhav** [comment]
and also check your pem file

**Comment by tejparekh** [comment]
I am having the Device token Registered. I have referred the "/example" from the repository. 
Nothing is happening when I am trying to send a Push notification from "PushWatch" tool recommended from the repository. 

I am getting the **"Message Sent"** but nothing happens on the app. The event is not triggered for "onNotification" 
Necessary code is added in the "AppDelegate.m" file. its the code that is mentioned in the repository documentation. 

Any idea why am I not getting any Remote Notifications? 
**I am working on the IOS device and I have a valid .pem file and device token.** 

Thanks

**Comment by batuhanorhn** [comment]
i have this problem. please help @zo0r

**Comment by matheusbaumgart** [comment]
Same here

**Comment by odedkeren1** [comment]
if you are not using firebase client then, the token that you see is the apn key and not the firebase key. to check if you configured your app correctly to receive messages use this:
go this url
https://solarianprogrammer.com/2017/02/14/ios-remote-push-notifications-nodejs-backend/

in section that starts with:"In order to send notifications to Apple’s servers..."
create server.js
and run it

**Comment by Aayushi1301** [comment]
Still same issue. I tried cloning the example project and followed installation steps in https://github.com/react-native-community/push-notification-ios but I am not able to receive remote notifications from firebase.
