### ISSUE TITLE
How to deal with different timezones for repeating local notifications?

### ISSUE THREAD

**Issue by cuttlas** [zo0r/react-native-push-notification#1209]
I want to set a local notification that triggers at a given time everyday (ex. 18:00) regardless of the timezone the user is in.  Right now, I'm doing something like this:

```javascript

  let firstNotification = new Date();
  firstNotification.setHours(18);
  firstNotification.setMinutes(00);

  PushNotification.localNotificationSchedule({
    id: ...,
    title: "My notification Title",
    repeatType: "day",
    message: "My Notification Message",
    date: firstNotification
  });

``` 
It works perfectly... unless the user changes his timezone (travels to another country). If, for example, he's is at GMT+2 and moves to GMT-6, the notification triggers at 10:00 instead of 18:00. How can I have the notification to trigger always at 18:00 even if the timezones changes?

**Comment by sunweiyang** [comment]
I currently resolve this by using UTC for defining the date.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC

**Comment by amhzjm** [comment]
Hi 
I am just trying something similar to what you are doing but the difference is I am calling the notification when the app in the background using appstate the problem is the notification show up immediately after closing the app and ignoring the time and date set for the notification ?! any help will be appreciated
