### ISSUE TITLE
[Android] onRegister() not called

### ISSUE THREAD

**Issue by gabeDevlift** [zo0r/react-native-push-notification#1295]
I've followed the installation instructions, and noticed that onRegister() is never called. I am not able to generate a push token. I am running it on a real device, Galaxy A30. I'm not using Firebase or any of the Google-Services files I've seen mentioned elsewhere.
Has anyone else run into this?

**Comment by ctopher7** [comment]
You need to include the google service file 
to your project in order to get fcm token

**Comment by gabeDevlift** [comment]
> You need to include the google service file
> to your project in order to get fcm token

@ctopher7 Thanks for your reply. Could you point me to where I can read about this? I don't see reference to fcm tokens or anything in the documentation for react-native-push-notification.

**Comment by ctopher7** [comment]
@gabeDevlift when you first set your project up on firebase, it tells you to download the google service json file (android) or plist file (ios) and there is an instruction to put it in your android/app folder if im not mistaken. Refer to you firebase console

**Comment by gabeDevlift** [comment]
@ctopher7 I'm not using Firebase at all. Do I still need Google Services?

**Comment by MahefaAbel** [comment]
I have the issue, @gabeDevlift > have you resolve it?

**Comment by arnaudambro** [comment]
onRegister was not called for me, until I put the `senderId` field, which is the `project_info:project_number` field of the `google-services.json` that you need to download from you firebase consol and locate in the `android/app` folder. 
And yes, to have push notifications (no need for local), you need to use firebase console, because that's the way Google knows your device and can send notifications to it.

**Comment by pauloXtr3m** [comment]
Same issue here, and i'm using Firebase. @arnaudambro where do you put the `senderId` ?
