### ISSUE TITLE
Update package to work with React's 0.60+ autolink

### ISSUE THREAD

**Issue by Baterka** [zo0r/react-native-push-notification#1352]
I am getting this error/warning when running build:
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-push-notification (to unlink run: "react-native unlink react-native-push-notification")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in
your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

Any plans to update this package to be able to autolink in React 0.60+?

**Comment by Dallas62** [comment]
Hi @Baterka 

Did you try to install the library without `react-native link` ?
I think the library already support auto link.

Thanks!

**Comment by SaeedZhiany** [comment]
@Dallas62 

Maybe I'm wrong but for auto-linking support in iOS there should be a file `.podspec` in the root directory of the project (I didn't find it in the master branch of the library) and for Android side, the library must use Androidx packages instead of the support library (if has any).

are the changes applied to this repository?

**Comment by SaeedZhiany** [comment]
@Dallas62 

Maybe I'm wrong but for auto-linking support in iOS there should be a file `.podspec` in the root directory of the library (I didn't find it in the master branch) and for Android side, the library must use Androidx packages instead of the support library (if has any).

are the changes applied to this repository?

**Comment by Dallas62** [comment]
Hi @SaeedZhiany 
This library doesn't have iOS specific implementation, it's based on [push-notification-ios](https://github.com/react-native-community/push-notification-ios).
For Android, there is a bug in the latest version of the library with androidx (accidentally removed) it's ok on master.
As I remember, I did not need to link the project on my project and on the [example](https://github.com/zo0r/react-native-push-notification/tree/master/example)
I will contact ASAP the owner of this repository to release the version.

**Comment by Dallas62** [comment]
A new version is available,
If it solves the issue, feel free to close this issue ! 😃
