### ISSUE TITLE
Can not receive Remote Notification on IOS

### ISSUE THREAD

**Issue by fspider** [zo0r/react-native-push-notification#1358]
It is working well on android but not working on ios.

So i want to ask if it is possible in this case.

My php server sends push notification through firebase cloud messaging.
So i was testing with firebase cloud messaging test function.

Does react-native-push-notification module works in this case?

If yes, could you share the guide which you use?

One thing : it was working with firebase-message library.

**Comment by chenop** [comment]
Confirm that with:
"react-native-push-notification": "^3.1.9"

I receive the message with react-native-firebase hooks (onMessage) but when invoking:
PushNotification.localNotification() nothing happens.

**Comment by fspider** [comment]
Nearly the same problem here.
Using with firebase-message, remote push notfication arrived when the app is on background.
But could not be handled. This means the onNotification function was not called.
So i am not sure where i have to focus on either RNPN or RNFB?

**Comment by awmoreira** [comment]
Same here +1

**Comment by chenop** [comment]
@fspider I think neither ☺️.
Firebase responsible for bringing the message (json) to the device - it does not support displaying it (or maybe support [basic integration](https://rnfirebase.io/messaging/notifications#notifee---advanced-notifications)).
for actually display the message you need 3rd party library, this is where react-native-push-notification should help us - (although it is not maintained since Aug 2019).
The thing is - for IOS - react-native-push-notification use https://github.com/react-native-community/push-notification-ios and if you'll debug it you see it calling this library.
So my answer is: your focus should be on https://github.com/react-native-community/push-notification-ios AFAIU

**Comment by fspider** [comment]
Remote push notification is working when i send notification using this Knuff test app.
But still not working with firebase cloud messaging function.

**Comment by michalderdak** [comment]
+ 1 over here as well

We are trying to have remote push notifications from Firebase on iOS. We believe that we have followed the setup to the last dot and it seems that not even the `onRegister` event is being triggered

**Comment by chenop** [comment]
Just to update, I solved the issue on IOS  by [uploading APNs file](https://firebase.google.com/docs/cloud-messaging/ios/certs) to firebase console.

**Comment by fspider** [comment]
Thanks for helping me.
I have solved this problem by sending directly 
Backend->APN Server->IOS App
Bacnend->Firebase->Android App.
It is working well.

Thanks.
