### ISSUE TITLE
Custom RepeatTime for IOS

### ISSUE THREAD

**Issue by allindeveloper** [zo0r/react-native-push-notification#1377]
Hello,

Please i see that android has the ability to add:
 repeatType:"time" and then a custom time i.e repeatTime:1000.

but this feature doesn't exist yet on IOS, any hope of it coming up soon, or any other recommendations?

**Comment by Dallas62** [comment]
Hi @allindeveloper 
I think you should look at [react-native-community/push-notification-ios](https://github.com/react-native-community/push-notification-ios) for this feature

**Comment by allindeveloper** [comment]
Yeah, thank you.
I did check that, which is what i use for my App. but it only supports repeatInterval:
minute, hour, day, week, month, year but it doesn't support time, which can allow me to add a custom time in milliseconds.

**Comment by Dallas62** [comment]
Hi,
I made a custom "service" in my App to handle this case, but it's because I need to change the message based on the date / events that can occur during in time.
You can made a loop to schedule as many notifications you need; on iOS there is no limitation as far as i know, on Android (Samsung) there is a limit of scheduled notifications. You will have to clear scheduled notifications when something change.

**Comment by allindeveloper** [comment]
ohh hmm, nice.

Thank You

**Comment by allindeveloper** [comment]
I was also thinking if can  also correctly set the fireDate to the future and i set repeatInterval to "week", then it should repeat the notification from that fireDate till the next week and so on like that...
