### ISSUE TITLE
Cannot have two separate channel names even if you have two separate channels

### ISSUE THREAD

**Issue by mirzaam786** [zo0r/react-native-push-notification#1408]
# Bug

As we now know, if we wanted to have more than one sound for a notification we need to have multiple channels. However the current implementation only allows one channel name (in the AndroidManifest.xml). There should be an option to add multiple channel names to this manifest or have it passed through in the notification request.

**Comment by Dallas62** [comment]
Hi, due to some limitation on the management of channels in Android (one channel for one sound / vibration pattern / importance etc...) and the current architecture of the library, I think this will not be implemented.
wix/react-native-notifications add an implementation by binding directly the android API. But doesn't handled scheduled notification.

**Comment by mirzaam786** [comment]
But this version already supports multiple channels with separate channel ID just need to also have separate channel names.

**Comment by Dallas62** [comment]
Hi @mirzaam786 
If you have an idea to implement this feature, PR is welcome 🙂
Actually channels are generated on the fly, which made this feature not so easy.
