### ISSUE TITLE
Local schedule notification at a particular time

### ISSUE THREAD

**Issue by ersachit** [zo0r/react-native-push-notification#1535]
I am trying to send a push notification at a particular time let say 8 PM daily. And I made changes like this but there are some unexpected behaviour is going on -

1. It doesn't trigger the notification at 8 exactly. 
2. It keeps trigging the PNs after some time (10, 20 mins), even if I set repeatType: 'day'

Here is the snippet I tried- 

        var now = new Date();
        now.setDate(now.getDate() + 1)
        now.setHours(20);
        now.setMinutes(0);
        now.setMilliseconds(0);
        PushNotification.localNotificationSchedule(
            message: "My Notification Message",
            allowWhileIdle: true,
            repeatType: 'day',
            date: new Date(now)
        });

Any help would be appreciated.

**Comment by Dallas62** [comment]
Hi @ersachit 
Probably a limitation in android itself which is restricting background work to avoid battery consumption. Maybe another method exist to be more precise on the time.
For the repeating problem, I will look into it since the library add +24h from the triggering time which can lead to misbehaviour such as:
day 1: 20h00
day 2: 20h10 (10min delay)
day 3: 20h10 (no delay)
day 4: 20h20 (10min delay)
day 5: 20h25 (5min delay)
day 6: 20h25 (no delay)
day 7: 20h35 (10min delay)
...
And finally the notification time can completely change over time.


When we expect something like this, even if there is a delay:

day 1: 20h00
day 2: 20h10 (10min delay)
day 3: 20h00 (no delay)
day 4: 20h10 (10min delay)
day 5: 20h05 (5min delay)
day 6: 20h00 (no delay)
day 7: 20h10 (10min delay)
...

**Comment by ersachit** [comment]
@Dallas62 Thanks for the quick reply.

I haven't checked it on Android yet. It is a behavior of the iOS device. I have set the notification of 8 PM in the night but I got few notifications before time. Ideally, it should trigger the only single notification in a day let say 8 PM but I got 10-15 in a day which is totally not what I was expecting. Is there any other way to achieve this?

**Comment by Dallas62** [comment]
Hi @ersachit 

For iOS this is not the right repository, and the iOS repository use the official way to schedule notification.
You may found information in Apple developer forum or stack overflow.
