### ISSUE TITLE
Clicking on action buttons opens the app

### ISSUE THREAD

**Issue by anton-thushara** [zo0r/react-native-push-notification#1610]
When the app is killed, clicking on action buttons opens the app, is there a way to run code in headless mode without opening the app.

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#notification-actions

**Comment by avlonder** [comment]
As a remark in the  same context: due to the bug #1452, I was forced to use localNotification when the app receives a remote push notification. If my app is killed and I tap the notification, the app is opened, even if I specify { invokeApp: false, actions: ['open'] } in the configuration. This happens with react-native-push-notification 5.0.1 on Android.
