### ISSUE TITLE
Android Notification bar limit

### ISSUE THREAD

**Issue by MahaGamaledeen** [zo0r/react-native-push-notification#1615]
# Bug

Application received only 24 notifications then stop receiving till clear notifications from notification bar

**Comment by MahaGamaledeen** [comment]
any one faced this issue please ?

**Comment by TaraSinghDanu** [comment]
I got only 19 notification

**Comment by Dallas62** [comment]
Hard limits can't be changed,
Regards

**Comment by TaraSinghDanu** [comment]
> Hard limits can't be changed,
> Regards

Hard limits means?

**Comment by Dallas62** [comment]
system limit / android limit

**Comment by TaraSinghDanu** [comment]
Thanks @Dallas62 
Dou you any idea about this
I am getting remote notification, when the app is in foreground and getting large icon.
But when the app is closed or in background state I am not getting the large icon in notification panel.

**Comment by eatoniottest** [comment]
This is a reference to solve this problem. Hope it can also be implemented in react-native-push-notification.
https://medium.com/mindorks/the-notification-limit-per-app-in-android-94af69a6862c
We are checking whether activeNotifications are within the required limits. Otherwise, we will cancel the oldest release notification from the status bar notification, and then notify the user with the latest one.
