### ISSUE TITLE
6.x.x Questions

### ISSUE THREAD

**Issue by cristianoccazinsp** [zo0r/react-native-push-notification#1668]
# Question

I've looked through the changelog, and it only mentions what has been removed, but not exactly what's the migration progress.  Can I get some examples of what is the expected pattern to setup a notification channel and use notifications now? How do we make sure the same channel is used for existing app installs? We don't want to break existing channels that users may have already changed.

For example, our app expects to use just a channel throughout its lifetime, so we only need to setup the channel once.  Do we still need to call the channel setup function on every app start? 

What happens if a notification is fired and if there's no channel? Hard crash, soft crash, just warning?

What happens if notification channel creation fails? 

@Dallas62  tagging you seem you seem the one responsible of the changes nowadays!

Thanks!

**Comment by Dallas62** [comment]
Hi @cristianoccazinsp 

In short, for the Channel part, important change:
- `channelId` becomes mandatory (warning if not provided) for `localNotification` and `localNotificationSchedule`
- Channel documentation: https://github.com/zo0r/react-native-push-notification#channel-management-android

**Can I get some examples of what is the expected pattern to setup a notification channel and use notifications now?**
 You can look the exemple project, it is up to date with changes. You must create your own channel then pass the right channel id to for the notification. ( Firebase also have a property to target the right channel ).

**How do we make sure the same channel is used for existing app installs?**
It's depends on your case. 
 - Local / Scheduled only => Application Upgrade doesn't have impact since the upgrade doesn't delete existing channels, just create channels needed and pass the `channelId`.
 - Remote notification with default channel from `com.google.firebase.messaging.default_notification_channel_id` => You can create a channel and change the value of `com.google.firebase.messaging.default_notification_channel_id` in `AndroidManifest`, this should not have impact.
 - You already manage notifications with your own channels => No impact expect an issue which is fixed
 - Remote notification with `channelId` in the firebase Payload (using default channel id prior to 6.0.0) => you will have to make the upgrade in two times. First create the channel with the "old" channel id. And if needed, create another channel with more appropriate settings (custom channel id).

**Do we still need to call the channel setup function on every app start?**
Repeated call to the function have limited impact, this may allow update the name and description.
From [Android documentation](https://developer.android.com/training/notify-user/channels):
> After you create a notification channel, you cannot change the notification behaviors—the user has complete control at that point. Though you can still change a channel's name and description.
> You should create a channel for each distinct type of notification you need to send. You can also create notification channels to reflect choices made by users of your app. For example, you can set up separate notification channels for each conversation group created by a user in a messaging app.

**NOTE:** not mentioned there but the `importance` can be decreased, but not increased. (somewhere in the Android documentation).

**What happens if a notification is fired and if there's no channel? Hard crash, soft crash, just warning?**
The library display a warning development, and from [Android documentation](https://developer.android.com/training/notify-user/channels):
> Caution: If you target Android 8.0 (API level 26) and post a notification without specifying a notification channel, the notification does not appear and the system logs an error.

**What happens if notification channel creation fails?**
`created` will be `false`, and the previous answer happen.
```js
  PushNotification.createChannel(
    {
      channelId: "channel-id", // (required)
      channelName: "My channel", // (required)
      channelDescription: "A channel to categorise your notifications", // (optional) default: undefined.
      soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
      importance: 4, // (optional) default: 4. Int value of the Android notification importance
      vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
    },
    (created) => console.log(`createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
  );
```

**Comment by cristianoccazinsp** [comment]
@Dallas62  thanks for the detailed response!

Can you take a look at the `importance` value? The docs show an int value (4) for `createChannel`, yet somewhere afterwards it shows a string value (e.g., high, low, max, etc.).

Could this be made more consistent? Can both values be used?

**Comment by Dallas62** [comment]
Hi @cristianoccazinsp 

Thanks for the feed back, I will take a look at this.
