### ISSUE TITLE
How to add action buttons on ios?

### ISSUE THREAD

**Issue by Aayushi1301** [zo0r/react-native-push-notification#1693]
`react-native-ios-notification-actions` package is suggested to use but since it's not actively maintained, is there an alternative? I just need action buttons on background push notifications.

**Comment by Dallas62** [comment]
Hi @Aayushi1301,

As far as I know, there is no alternative that works with the current library.
And I don't have time to implement this right now but it would be great if some have some times to fix the mentioned project.
We will find a way to keep the new repository maintained.

If you don't need scheduled notifications, `react-native-notifications` could be the right library to use.

Regards.

**Comment by Aayushi1301** [comment]
> Hi @Aayushi1301,
> 
> As far as I know, there is no alternative that works with the current library.
> And I don't have time to implement this right now but it would be great if some have some times to fix the mentioned project.
> We will find a way to keep the new repository maintained.
> 
> If you don't need scheduled notifications, `react-native-notifications` could be the right library to use.
> 
> Regards.

@Dallas62 `react-native-notifications ` doesn't support image in local notification for android. So I had to look for an alternative.
My requirements are: 1. show rich notifications and action buttons on both ios+android while the app is in background/dead. 
Packages I tried: react-native-firebase/messaging-doesn't allow actions.
react-native-notifications-doesn't allow rich notifications for android.

Can you suggest a libbrary/libraries to suit my requirement please.

**Comment by Dallas62** [comment]
You will probably need to mix library to allow all the features... 

There is a huge lake in notifications library due to the large amount of parameters and the difficulty to test all features.

You have 4 options:
- Make a PR with the missing part 😉 
- Mix libraries for iOS and Android (hopefully you will find all features in libraries).
- Create you "own" module by implementing you need in native and bind the API with the JS side.
- Find a commercial library that fit you needs.

Be aware it takes too much times to implement all features in open-source. I planned in long-term to help the iOS team but it's actually impossible.

Regards

**Comment by Dallas62** [comment]
Changes have been made on the iOS library, can you check the documentation to know if this fit your needs ?
(Not available directly from this library actually)
