### ISSUE TITLE
onNotification called only when notification toast is tapped

### ISSUE THREAD

**Issue by strawberry-code** [zo0r/react-native-push-notification#1788]
Before posting details about the configured plugin I would ask you if you may know what are the possible causes for this issue: onNotification eventi is fired only when notification toast is tapped. The desired behavior is to get onNotification fired when the remote notification arrives even if the user doesn't tap it.

`configurePushNotifications()` is called outside of a RN component.

RN version: 0.63.2
RN Push Notification version: 4.0.0

```
function configurePushNotifications() {

  PushNotification.configure({

    onRegister: async token => {
      store.dispatch(updateNotificationsInstallationToken(token.token));
    },


    onNotification: notification => {
      console.log('🎈 push arrived! (' + Platform.OS + ')') // We get this balloon only if the user taps the notification...
      console.log('push details: ' + JSON.stringify(notification))

      ...

      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
    senderID: gcmSenderId
  });
}
```

**Comment by Dallas62** [comment]
Hi @strawberry-code 

You can look at: https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md#about-notifications

Best regards,

**Comment by mstaicu** [comment]
I'm also interested in having the `onNotification` callback called whenever a scheduled local notification is received, instead of the `onNotification` being called when I tap on the notification. From what I'm reading on the link that you shared it seems that I might be wanting to look into "silent remote push notifications", correct? If yes, then, can I achieve this without using a server? Before going off to Google, it might be worth asking if you have an example of how one might achieve this or how one has achieved this.

Also, thanks for all the hard work on the library!

**Comment by stothet** [comment]
@Dallas62 have same query as @mstaicu

**Comment by Dallas62** [comment]
Hi @mstaicu 
This feature will not be implemented because iOS cannot handle it.
Also not that scheduled notification doesn't work well on Android due to Energy saver killing the application.
Regards,

**Comment by mstaicu** [comment]
@Dallas62 any recommendations on how one might go about achieving the request behaviour? https://github.com/zo0r/react-native-push-notification/issues/1788#issuecomment-757365398

**Comment by Dallas62** [comment]
Hi @mstaicu 
As said previously, scheduled notifications cannot trigger `onNotification` before being tapped.
And remote notification needs to be send from an external services (your server or some SaaS plateform).
Regards,
