### ISSUE TITLE
How to get all subscribed topics?

### ISSUE THREAD

**Issue by ksetrin** [zo0r/react-native-push-notification#1840]
# Question

I use topics on my project and sometimes users tell me they have a push messages not related to user. 
This happens when a user logs out and logs in to another account
And finally I fixed that issue, I started to keep subscribed topics in AsyncStorage

But, what if a user clear all data (android)?
Do I stay subscribed to the push notifications?

What if unsubscribe processing will be terminated (or early), but user already logged out?
This will mean that the user is already logged out but still subscribed to topics

**The question is: How to know all subscribed topics in any time?**

I found one way to [Get all subscribed topics from firebase cloud messaging](https://stackoverflow.com/questions/37987821/get-all-subscribed-topics-from-firebase-cloud-messaging) from stackOverflow, but this method does not work for iOS (not tested for Android, will do it soon)

So, assume it works for android then how to get the same for iOS?

**Comment by Dallas62** [comment]
Hi @ksetrin 
This library is not a Firebase Library but a way to get notification on both Android and iOS. Since Android doesn't have a default notification provider, Firebase was chosen to acheive the remote part and it's optional.
For iOS, there is no support provided with Firebase with this library, iOS use the default provider: Apple Push Notification (APN).
If you want to use Firebase, please use RNFirebase/message.
Regards,
