### ISSUE TITLE
setApplicationIconBadgeNumber not working 

### ISSUE THREAD

**Issue by Leehee1on** [zo0r/react-native-push-notification#1849]
package.json
   "react-native": "0.63.4",
    "react-native-push-notification": "^7.2.0",
    "@react-native-firebase/messaging": "^10.5.1",

android/app/build.gradle
 dependencies {
    implementation project(':react-native-push-notification')
    implementation "me.leolin:ShortcutBadger:1.1.22@aar"
 }

index.js

import PushNotification from 'react-native-push-notification';
PushNotification.setApplicationIconBadgeNumber(2);

Is Ios wolking 
android not working..

I don't know much about Android. But setApplicationIconBadgeNumber Want to set up in React Native

**Comment by Dallas62** [comment]
Hi @Leehee1on 
Unfortunately, it's not working the same way on iOS and Android.
https://github.com/zo0r/react-native-push-notification#set-application-badge-icon
https://developer.android.com/training/notify-user/badges

On iOS it's an "absolute" badge stick to the application. 
On Android (recent version) the badge is stick to the notification, so you should not be able to add a number to the application without a notification.

The current library use: https://github.com/leolin310148/ShortcutBadger as a workaround, but it's not fully maintain due to the huge number of Android devices which handle the application icon differently...

I recommend you to think differently on Android and iOS for the badge number.

Regards,

**Comment by Leehee1on** [comment]
Hi @Dallas62.

i want use ShortcutBadger in RN . 
ReactNative change in set Badge Number ?

**Comment by Dallas62** [comment]
As explained, this library use ShortcutBadger, **BUT** it's not fully maintain due to the huge number of Android devices which handle the application icon differently...
Which means: This may work on Android device, **BUT** there is no warranty.
If you take a look to issues you will see the huge number of non-supported devices https://github.com/leolin310148/ShortcutBadger/issues

As said, there is no native way to handle the badge number on all device. You should change the way you manage badge number based on the OS of the device.

Regards,

PS: Feel free to fork ShortcutBadger and fix all devices if you have time and you really want this feature.

**Comment by Leehee1on** [comment]
humm..
i'm not android developer 
give me example code?

**Comment by Dallas62** [comment]
I gave you the repository link.

**Comment by Leehee1on** [comment]
ok. 
Lack of explanation example ,
last question
surely badge related channel?

**Comment by Dallas62** [comment]
https://developer.android.com/training/notify-user/badges

**Comment by Dallas62** [comment]
> Lack of explanation example ,

As explained, this library use ShortcutBadger, so if you use:
```js
import PushNotification from 'react-native-push-notification';
PushNotification.setApplicationIconBadgeNumber(2);
```

You already use `ShortcutBadger` in the version 1.1.22, refering to your post:
```
implementation "me.leolin:ShortcutBadger:1.1.22@aar"
```
I cannot help you more since you have all details.
If you want exemple to fix devices on `ShortcutBadger` repository, there is no exemple since it depends on Manufacturer's  documentation. If it was an easy fix, `ShortcutBadger` would be already fixed.

**Comment by Leehee1on** [comment]
I was using ShortcutBadge before the answer came, but suddenly it didn't work. But when I send a Google message, it suddenly works. First thanks.
