### ISSUE TITLE
(Android) Local notifications are not stacking in the notification tray. Instead, they are being replaced by the new ones.

### ISSUE THREAD

**Issue by Agusfn** [zo0r/react-native-push-notification#2041]
Hello, I am using the library to display local notifications on Android with method **PushNotification.localNotification()** 
But when I send multiple notifications, one after the other, they don't stack in the device notification tray. The new one just replaces the old one, and there's always only one.

I would like to know if this is possible.

**Comment by schimini** [comment]
@Agusfn I suppose you're using the code snippet in the docs for local notifications. If so the issue is that you're using the `id: 0` . That makes the notifications replacing each other since their identifier is the same. You can just delete that parameter and it will use a random id solving your issue. Hope this helps.

**Comment by Agusfn** [comment]
@schimini Thank you! That was the correct answer. Couldn't find info anywhere about it.
