### ISSUE TITLE
Remote Notification received but not showing pop up in android ! Not working properly .

### ISSUE THREAD

**Issue by joy-mollick** [zo0r/react-native-push-notification#2225]
I have spent almost 2 days over this to make push notification work but failed , some versions of this package work but failed in relaese mode . Some verisons of this package are able to receive remote notification but not be able to show notification like pop up . I used different versions of firebase messaging or many other stuffs regarding this , but failed . I wonder how other people can solve these issues , is there anyone to maintain this package or this package has been damaged ? Why so much errors ? Why such different behaviours of this package and there is no proper solution of these issues . People had to waste time over this , nothing else !

**Comment by Dallas62** [comment]
Hi,
Nice to see a reproducible exemple, that will really help to understand your issue !
Feel free to read the readme for information (since we can't help you without information) and Troubleshooting file or issues.

Also look at https://github.com/zo0r/react-native-push-notification#state-of-the-repository

Regards
