### ISSUE TITLE
Notification not working for App store version

### ISSUE THREAD

**Issue by iamrohitagg** [zo0r/react-native-push-notification#2289]
Hi everyone, I am using firebase cloud messaging for remote notification. The app works fine and I am able to receive notification when the app is installed using diawi on real device.
But the problem is I am not able to receive notifications when I upload the application to App Store and download the app from there.
Please help!!

**Comment by edizsuleyman** [comment]
Hi @iamrohitagg , 
I am not sure if this helps or not but this might be an issue related to you firebase cloud and not the library itself. We had a similar issue, we use Azure Notification Hub, and it turned out that for production/live version we had to add a new IOS key for the hub to process notifications on live.
I hope it helps a little.
