### ISSUE TITLE
Feature Request: Schedule Event

### ISSUE THREAD

**Issue by thejamespinto** [zo0r/react-native-push-notification#229]
I love this project, but I don't think `PushNotification.localNotification(` and `PushNotification.localNotificationSchedule(`are enough, I believe we need a `PushNotification.schedule(` function here because a lot of people will need to simply evaluate whether or not they **need** to send a local notification, this would be good for reminder apps.

I'll lay out a simple scenario to illustrate better why I think this lib should have this feature.

```
I set a GPS location named "Home"
Every 5 minutes,
If I am currently 100 meters away from "Home"
I want to send a notification with text "Go back home now, you are grounded."
```

This is impossible to achieve with only those 2 functions because they don't allow us to evaluate whether or not to send the notification.
I believe the same could be achieved with a similar DSL, here is a rough draft.

``` js
PushNotification.configure({
    onSchedule: function(notification) {
        console.log( 'SCHEDULE:', notification );
        if (is100MetersAwayFromHome())
            PushNotification.localNotification(notification);
    }
});

var date = new Date(Date.now() + (5 * 60 * 1000)); // 5 minutes from now
var notification = {
    message: "Go back home now, you are grounded."
};
PushNotification.schedule(date, notification);
```

Yes, this could be implemented by another lib, but I believe they belong together because we already have to add several `receivers` and `services` to `AndroidManifest.xml`.
I believe we could even reuse one of those, since the code is mostly scheduling a piece of code to run another piece of code that dispatches the notification.
All I am saying is that maybe we could have another piece of code in between that. Somewhere around here https://github.com/zo0r/react-native-push-notification/blob/2f80b1/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L124-L127 

What do you guys think?
Please, leave your comments below. ❤️

**Comment by npomfret** [comment]
Is it currently possible to schedule a single local notification that fires _silently_ (i.e. no noise, vibration or text) on iOS and Android?  If so you should be able to use this idea to continually schedule repeating "silent" notifications.  You simply schedule the next one inside your `onNotification` method.  

If the user needs an alert (because they have strayed too far from home in your example) then send  an additional "noisy" local notification (with sound, vibration and text - whatever) which will appear in the notification center. Simultaneously you schedule the next "silent" notification to fire in 5 minutes from now... and repeat.

So you use "silent" scheduled notifications to repeatedly do something.  And then (optionally) "noisy" local notifications to alert the user.

**Comment by thejamespinto** [comment]
@npomfret I don't think it is possible to send a silent notification.
Can you help me figure this one out?
I believe it would be incredibly beneficial to this lib.

**Comment by thejamespinto** [comment]
@npomfret I actually pretty much tried everything I can and nothing worked. 😭

**Comment by mohamedabusrea** [comment]
@thejamespinto did you find a solution to achieve the  "onSchedule"
