### ISSUE TITLE
Headless JS tasks

### ISSUE THREAD

**Issue by stovmascript** [zo0r/react-native-push-notification#251]
RN v0.36 added [this feature](https://github.com/facebook/react-native/commit/3080b8d26cfbfdb4f940ad987c02563dee624d92) and I'm wondering if it could be used for background and closed app notification handling, similar to what was added with #220 ...

**Comment by mikelambert** [comment]
It'd be good to clarify what benefits we expect headless JS tasks adding, feature-wise, that is not already available as part of #220 (Which I had written prior to JS tasks being released, and so works on older versions of RN)

One benefit is the simplification of code in this module, by using the 0.36 code instead. Turns out our codepaths are basically identical.. Though by making the feature 0.36-only, after just implementing it for everyone, people might complain. :P (ie, my app is not yet on 0.36)

Another potential benefit is mentioned in the docs:
```
+ * If you're starting a {@code HeadlessJsTaskService} from a {@code BroadcastReceiver} (e.g.
 + * handling push notifications), make sure to call {@link #acquireWakeLockNow} before returning from
 + * {@link BroadcastReceiver#onReceive}, to make sure the device doesn't go to sleep before the
 + * service is started.
```

...as my code in this module doesn't touch the wakelock (though we could reimplement that chunk of code too)

**Comment by chirag04** [comment]
+1 for headless JS task. Not sure what is the min supported RN version but 0.36 should be reasonable. Current RN release is 0.40.

**Comment by tmaly1980** [comment]
This is has been sitting idle for over a year, any idea whether this can be implemented? Android is having a bug where it's relaunching my app if the app is closed, when I'm using react-native-navigation. I need a way around that.
