### ISSUE TITLE
Tapping a notification in the notification centre can result in app being relaunched! 

### ISSUE THREAD

**Issue by npomfret** [zo0r/react-native-push-notification#281]
To reproduce:

1. Send an Android notification that does not contain a `data` element while the app is running in the background.

2. Tap on the notification in the notification centre.

3.  Repeat a few times.

What I noticed is that when tapping the notification my app appeared to re-launch itself even though it was already running.  After trying a couple of times I realised that the app was launching multiple copies of itself - each tap resulted in a new instance of the JS app... but only 1 runtime - so I have multiple apps running side by side with a single UI!

It does not appear to happen if the push notification contains a `data` element.

**Comment by TriangleIL** [comment]
I'm having this same exact issue.  Considering moving to a "data" payload, but would prefer to stay with the "notification" payload if at all possible.  Any thoughts around this one?

**Comment by npomfret** [comment]
I've not fixed it. @mikelambert have you any idea what's happening here?

**Comment by mikelambert** [comment]
So without a `data` payload, the `onMessageReceived` will get called when opening the notification. And this is where my changes get run, so it's likely related to my code. :( How are you verifying that there are multiple "apps" running, and what does that mean exactly?

This *might* be fixed by switching to  [headless tasks](https://facebook.github.io/react-native/docs/headless-js-android.html) added in RN 0.33. Are we perhaps willing to break compatibility with older RN versions at this point? I'm focused on other things at the moment for the next couple months, but can do the migration the next time I dig into the mobile/notification code.

Alternately, comparing the [Headless JS code](https://github.com/facebook/react-native/blob/3080b8d26cfbfdb4f940ad987c02563dee624d92/ReactAndroid/src/main/java/com/facebook/react/HeadlessJsTaskService.java#L96) and the [RN-PN code](https://github.com/zo0r/react-native-push-notification/blob/d9cd728c044d488c7dcb5f1bb71da9d3aafe1ceb/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java#L57) developed independently, it looks like the only thing I had forgotten was the [listener-removal](https://github.com/facebook/react-native/blob/3080b8d26cfbfdb4f940ad987c02563dee624d92/ReactAndroid/src/main/java/com/facebook/react/HeadlessJsTaskService.java#L108) (maybe multiple identical listeners are the source of the problems?)

**Comment by jk94** [comment]
@npomfret @mikelambert thanks for your answers. I fixed my problems with an attribute in my AndroidManifest.xml. I added `android:launchMode="singleTop"` to the main activity element.

```xml
<activity
   android:name=".MainActivity"
   android:label="@string/app_name"
   android:launchMode="singleTop"
   android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
   ...
</activity>
```

Maybe this helps s.b. else!

**Comment by npomfret** [comment]
@mikelambert sorry for the slow reply, been travelling.  I like your theory about the listener removal.  

Have you tried replacing your code with the built in RN headless tasks?

**Comment by mikelambert** [comment]
Nope. Please see the second paragraph of my message above. :p

**Comment by Noitidart** [comment]
The deep linking docs recommend `"singleTask"` -  https://facebook.github.io/react-native/docs/linking.html - 

![](http://i.imgur.com/XjN46uL.png)

I havent tried the  push notification module yet. But does anyone know how that compares to with @jk94 approach above of `android:launchMode="singleTop"`?

**Comment by PokoGroot** [comment]
Hi i'm currently having this issue, when app is in background and show localnotification it launch the app when i clicked on notification.
Is there any way to prevent app from launc ?
I'am using react-navigation

**Comment by raymatos** [comment]
Why was this closed?  What was the solution?

**Comment by mahipalsingh-syt** [comment]
@raymatos issue still there with local notification in android , onNotification is not working...  

@Dallas62  why this query has closed ? :(

**Comment by nikolajskov** [comment]
@Dallas62, what is the solution that fixes this issue?
I'm still seeing the issue with version 7.3.1. I've tried the solution suggested by @jk94 with using android:launchMode="singleTop" and it seems to fix the problem. Is this the correct solution?

**Comment by Dallas62** [comment]
Hi @nikolajskov 
This is the correct solution to avoid this issue.

**Comment by nikolajskov** [comment]
Thanks @Dallas62

**Comment by redefinered** [comment]
I ran into this issue but with different setup. My app is not invoking the onNotification func because I have react native splash screen installed which modifies android main activity and that means the data that comes from notification library does not reach the react activity.

This post has a fix in this particular scenario:

https://github.com/crazycodeboy/react-native-splash-screen/issues/289

I hope that helps anyone!
