### ISSUE TITLE
Support for Rich Notifications iOS 10

### ISSUE THREAD

**Issue by jqn** [zo0r/react-native-push-notification#327]
Hi, I was wondering if there is support the iOS 10 new feature rich notifications. I was looking everywhere and can't seem to find an answer.

![screen shot 2017-01-03 at 2 34 00 pm](https://cloud.githubusercontent.com/assets/9710893/21623865/bffcf324-d1c1-11e6-850d-c843a9c9c33b.png)

**Comment by shercoder** [comment]
@jqn I came across this issue as well and turns out this is a limitation in `RCTPushNotificationManager`.  I created a issue on RN project https://github.com/facebook/react-native/issues/12008. But It is closed because there are no plans for adding this right now. 

I have created a Product Pains post. Please up vote this if you'd like this feature integrated. 
 https://productpains.com/post/react-native/support-for-ios-10-rich-push-notifications

**Comment by azamouchi** [comment]
@jqn  This could be helpful
https://medium.com/@martco/triggering-ios-actionable-push-notifications-via-react-native-7990a6a3c3f4#.s6086xfjb

**Comment by farshid1** [comment]
@azamouchi I tried that but the `didReceive` is never called. Were you able to make it work?

**Comment by azamouchi** [comment]
@farshid1 i didn't tired that, i just came across your issue and the referenced article at the same tame, so i thought that could be helpful.
