### ISSUE TITLE
Not getting Notification on Android when app in kill state.

### ISSUE THREAD

**Issue by imbudhiraja** [zo0r/react-native-push-notification#388]
RN -0.39
Android - 5.0.1, 5.1, 6.0

**Comment by ArtemKosiakevych** [comment]
You need to enable autorun your application in settings for receiving notification on Android

**Comment by imbudhiraja** [comment]
Hi @ArtemKosiakevych can you plz describe a bit more.

**Comment by chetan1507** [comment]
I think we'll also need to add 2 more permissions in the AndroidManifest.xml.
Solved the issue for me.
```
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<uses-permission android:name="com.google.android.c2dm.permission.SEND" />
```

**Comment by mitesh-mutha** [comment]
Hi @chetan1507 

Would this be required for scheduled local notifications as well ?

I am facing the issue that a scheduled local notification is not being displayed. The notification does not come if I have scheduled it after a comparatively long duration but it works if the scheduled duration is lower. I believe it has something to do with the app state.

**Comment by chetan1507** [comment]
@mitesh-mutha  You are correct. 

New Mi (Xiaomi) and Huawei mobiles have this issue of clearing the app state by default if not in use. Hence you'll not get any sort of such notifications because technically, the app is in the killed state.

I haven't gotten around this problem as it is more of a customer device thing and you cannot ask each of your customers to do custom setting for your app specifically.
