### ISSUE TITLE
Amazon SNS push notifications

### ISSUE THREAD

**Issue by facuacostag** [zo0r/react-native-push-notification#414]
Hello everyone! Has anyone tried to get remote notifications from Amazon SNS? How did you manage to do that? I'm able to send all my information to Amazon but I don't know how to handle the notifications on my Android app and the documentation here is...useless regarding this topic. Cheers!

**Comment by arunkumarrmrj** [comment]
Hi @FacuAcosta 

I've a same issue ,
If you have any docs or simple sample application could you please share with me

**Comment by KatSick** [comment]
I managed to send push notification from SNS, however I, can't see my custom data in message

**Comment by lukebrandonfarrell** [comment]
@KatSick did you manage to figure out how to see the custom data?

**Comment by KatSick** [comment]
@lukebrandonfarrell nope :(

**Comment by lukebrandonfarrell** [comment]
@KatSick I figured it out. I'm using [wix/react-native-notifications](https://github.com/wix/react-native-notifications) instead of [zo0r/react-native-push-notification](https://github.com/zo0r/react-native-push-notification) for a start. The message has to be formatted in SNS as such (for example using APNs).

```
{
"APNS_SANDBOX":"{\"aps\":{\"alert\":\"My message\"},\"custom_id\":\"1234\",\"custom_name\":\"my_data\"}"
}
```

The underlying problem was with the way I was using AWS SNS. Using message attributes instead of JSON payloads. This could potentially work with [zo0r/react-native-push-notification](https://github.com/zo0r/react-native-push-notification), although I have not tried it.

**Comment by builtbyproxy** [comment]
@lukebrandonfarrell 	this is awesome!

The payload: 
```
{
"GCM": "{ \"data\": { \"message\": \"Test\", \"foo\": \"Bar\" } }"
}
```

Generates this notification:
![image](https://user-images.githubusercontent.com/16897508/48322185-03403580-e672-11e8-89f1-4e6d894633ba.png)
