### ISSUE TITLE
App closed onNotification

### ISSUE THREAD

**Issue by RWOverdijk** [zo0r/react-native-push-notification#429]
Awesome project :)

I have everything working, but one thing isn't. When my app is closed (hard closed) onNotification doesn't get called when the user pressed the banner. It works when the app is in the background, or when the phone is locked, just not when the app is closed.

How can I get this to work?

**Comment by hughnguy** [comment]
Running into the same issue. Have you figured out a solution?

**Comment by vidimitrov** [comment]
@RWOverdijk @hughnguy 
As far as I am currently with this problem, I realized that this problem is happening because the app is getting cached as a background process.
So the first time when the app is closed, it goes through the **onNotification** handler and start the background process. If you want the **onNotification** handler to be executed when the user tap on the push notification from the tray, you have to kill the background process. Then once it is killed, it goes through the handler and this time the notification payload contains **userInteraction: true**
I am not sure yet if this is a problem with the library or something that you should handle manually. Will keep looking into it. Keep in mind that killing manually the cached process is not recommended.
What do you think? Have you figured it out already?

**Comment by vidimitrov** [comment]
I found the solution from one of the other issues. The following code works exactly for the case when your app is closed (killed) and you receive a push notification and then tap on it.

`componentWillMount() {
    PushNotification.popInitialNotification(notification => {
      console.log('Initial notification: ', notification);
    });
  }`

Keep in mind to execute it in the **componentWillMount()** method of your root component.

I am not sure why this is not properly documented, but for me this was the most important functionality of these module. The push notifications are meant to be tapped from cold start and not when the user is using the app (foreground). If you are not able to handle the tap in this situation, you are not going to be able to react on it (redirect internally or do something else) or measure your engagement strategy.

@zo0r @npomfret It would be really nice to take a look at it and document it as you think its best.

**Comment by shrutic** [comment]
Thanks for detailed info @vidimitrov . For me the notification inside the popInitialNotification is null and does not contain any information. Any thoughts on what I could be missing here? I made sure I was calling it inside the componentWillMount() of my root component. And when I tap on the notification after the app is killed, the notification is set to null inside the popInitialNotification. Any thoughts on what I might be missing here? I do have the notification successfully work when user tap on notification when the app is in background

**Comment by vidimitrov** [comment]
@shrutic this module is not implementing the functionality for iOS. It just bridge all the functionality from the react-native push notifications module for iOS - [PushNotificationsIOS](https://facebook.github.io/react-native/docs/pushnotificationios.html#getinitialnotification), so I would suggest looking into their documentation of how to use it properly.

I never had to deal with push notifications for iOS, so far but I would suggest you looking into the payload of the notification that you send. Of what I know there should be a difference in the payload that you are receiving for the different platforms. For example in my integration I am using the FCM API and I am sending only the **data** property with the payload and I am handling what will happen locally. And if I am not wrong for iOS you are supposed to use the **notification** one.
