### ISSUE TITLE
localNotificationSchedule generates multiple notifications

### ISSUE THREAD

**Issue by owenauch** [zo0r/react-native-push-notification#453]
Hi, I'm trying to implement localNotificationSchedule to trigger at a specific date that I receive from an API. But it seems that no matter what component I place this function in, it gets triggered multiple times, which results in many of the same notification being triggered at that time. How can I implement this so that it won't repeat notifications?

**Comment by AmmarHasan** [comment]
@owenauch I am facing the same issue. Can you please tell how did you solve this issue?

**Comment by kevinEsherick** [comment]
@owenauch @AmmarHasan Any luck? Anyone else? There's gotta be someone here who is successfully using localNotificationSchedule. Im having the same issue. The notifications usually repeats once, but has repeated as many as 4 times. Obviously any repeats renders it unusable. I'll let you know if I come up with something

**Comment by kevinEsherick** [comment]
@emilany I just ended up using a different library. Not sure I ever really tried to find a fix for this, the other library just made more sense for me—I'm using firebase so I went with react-native-firebase. If you're not using other firebase services it's a little bit more work for just push services since you need to set up a firebase project and config and all, but it works and has a lot of documentation and a whole team supporting it

**Comment by snehaChaudhari** [comment]
I'm also facing same issue, any solution??
