### ISSUE TITLE
onRegister the token null

### ISSUE THREAD

**Issue by mikhi** [zo0r/react-native-push-notification#584]
Hi,
great package so far.

I have a question which is related with an issue:
When i open the app for the first time (after install), the token is not generated. The token is null.

Which is the best approach to get the token if the onRegister method returns token as null?
Do i have to recall this function in other screen of the app? 

Please help me with some code examples. 
Maybe something like:

`PushNotification.onRegister((token)=>{ console.log(token); });`

Thanks,
Mihai

**Comment by mikhi** [comment]
Can someone please advise/help me how to proceed in my case?

**Comment by tonygriv** [comment]
Same here

**Comment by tonygriv** [comment]
In XCode Capabilities tab you should turn on  Push notifications

**Comment by brascene** [comment]
Same here, setup all as described, allowed push notifications but token is still null..

**Comment by RobertStuff** [comment]
@mikhi have you found a way to make this work?

**Comment by hugoh1995** [comment]
Same problem here.

**Comment by brascene** [comment]
My issue was caused by not turning on the Push notifications capability in XCode, but however iOS is a bit harder to setup than android, make sure the following:

1. correct implementation of this npm package as described in documentation
2. make sure the push notification capability is turned on in XCode
3. make sure you've correctly set up the certificates provisioning profiles in Apple developer account (and also downloaded them inside XCode-Preferences-Account)

Hope this helps.

**Comment by RobertStuff** [comment]
@hugoh1995 Yup its already working.. I use Reactotron for logging but somehow it doesn't show the token.. I just see it when I do console.log! I think its an issue on Reactotron... Thanks anyway..

**Comment by adirzoari** [comment]
same here in android . how did you solve it?

**Comment by RobertStuff** [comment]
I log it via the console..
