### ISSUE TITLE
ios payload lost when clicked

### ISSUE THREAD

**Issue by vvavepacket** [zo0r/react-native-push-notification#587]
Anybody encountered iOS payload (notification.data) is lost when a push notification is clicked? When I clicked it, the notification.data becomes an empty object {}

**Comment by Eyesonly88** [comment]
Because on iOS, the notification data comes from the `userInfo` property. 
e.g:
```
{
   message: 'test notification',
   userInfo: {
    myData: 'hello'
   }
}
```
So when creating a notification, any additional data need to be in a `userInfo` prop and when the notification is received, `notification.data` will be populated with whatever is inside `userInfo`. So if there is no `userInfo` prop at the time of creating the notification, then the `notification.data` prop will be empty.

Hope this helps someone in the future.

**Comment by trspecht** [comment]
Thank you so much for this @Eyesonly88! Works like a charm!

Just adding that if you're also using this for Android, you can register the notification under `userInfo`, but when you grab that data, you need to look under `notification.data.myData`, instead of `notification.userInfo.myData`.

**Comment by paul-doherty** [comment]
@trspecht how did you get that to work on Android? Isn't userInfo Android only?

**Comment by paul-doherty** [comment]
Nevermind, this worked for me https://github.com/zo0r/react-native-push-notification/issues/384
