### ISSUE TITLE
Notice: Please give access to contributors to improve this package

### ISSUE THREAD

**Issue by calcazar** [zo0r/react-native-push-notification#725]
It really stinks that this package has sooo much potential and soo many people wanting to see it succeed and yet, there is no support.

I applaud @zo0r for getting the package as far as it did, I think we all do. But I think that a majority of the people using this package also feel like it's time to hand it off to someone (be it the react community or just contributors). You did a good job man and if you want credit, I'm sure you can work something out so you're name is embedded forever always but please.. please let this package move forward.

At the moment I'm sadly looking for alternatives since this package has fallen too far behind. Let us update it and polish it up!

**Comment by rikur** [comment]
I think he's too busy creating an altcoin: https://siglo.com/ :)

**Comment by likern** [comment]
@calcazar Have the same feeling.

- A lot of bugs are not really bugs, but more questions or other not relevant info
- "Bugs" are not closed
- Event PR are not handled properly

@Gp2mv3, could you give access to repository? There is a lot of things should be improvide - documentation, triage bugs / PRs. Now no one is looking even at PRs. 
I see you are the most contributor.

I and @calcazar would glad to help improving this package. Because I don't want to fork project. That's not the best option I think.

**Comment by Gp2mv3** [comment]
I can't give access to the repo, only @zo0r can. :disappointed:
