### ISSUE TITLE
android setApplicationIconBadgeNumber doesn't  work

### ISSUE THREAD

**Issue by NiuQiaoling** [zo0r/react-native-push-notification#756]
PushNotification.setApplicationIconBadgeNumber(6)  doesn't work in android

**Comment by Gp2mv3** [comment]
As stated in the README, you need to use ShortcutBadger: https://github.com/leolin310148/ShortcutBadger

**Comment by cristianoccazinsp** [comment]
@Gp2mv3 The docs states that it uses ShortcutBadger, but it doesn't state anything about you having to manually use it.

Looking at the source code, it seems like this library does all the required work in order to use ShortcutBadger when this function is used in Android.

Perhaps, the documentation is not clear enough. What steps are required to have PushNotification.setApplicationIconBadgeNumber to work in Android? I'm facing the same issue.

**Comment by marioot** [comment]
This is still an issue.

**Comment by michaelVictoriaDev** [comment]
This is still an issue.

**Comment by Dallas62** [comment]
Already answered in other issues.
Can't be fixed, related to an external library and not the official way to use badges on Android.
Regards
