### ISSUE TITLE
 java.io.IOException: INVALID_PARAMETERS

### ISSUE THREAD

**Issue by liweijieok** [zo0r/react-native-push-notification#858]
Hello, i use you react-native-push-notification，run on the Android Api 27. Then in the `RNPushNotificationRegistrationService` class occur bellow error;
 
call(in the RNPushNotificationRegistrationService.java ):

```
try {
            String SenderID = intent.getStringExtra("senderID");
            InstanceID instanceID = InstanceID.getInstance(this);
            String token = instanceID.getToken(SenderID,
                    GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
            sendRegistrationToken(token);
        } catch (Exception e) {
            Log.e(LOG_TAG, TAG + " failed to process intent " + intent, e);
        }
```

error:

```
NPushNotification failed to process intent Intent { cmp=com.lalamove.huolala.lalaclient/com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService (has extras) }
    java.io.IOException: INVALID_PARAMETERS
        at com.google.android.gms.iid.zzaf.zzk(Unknown Source:420)
        at com.google.android.gms.iid.zzaf.zzj(Unknown Source:0)
        at com.google.android.gms.iid.zzaf.zzd(Unknown Source:180)
        at com.google.android.gms.iid.InstanceID.zze(Unknown Source:60)
        at com.google.android.gms.iid.InstanceID.getToken(Unknown Source:98)
        at com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService.onHandleIntent(RNPushNotificationRegistrationService.java:25)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by vyobukhov** [comment]
@liweijieok have you resolved this issue? I'm faced the same problem after switching to FCM and 26 api version

**Comment by dattran97** [comment]
I'm faced the same problem too, but after re-checking, I realize that I forgot to add senderID in 
.configure(onRegister: void, onNotification: void, gcm = 'ADD_SENDERID_HERE')

**Comment by AlexejKutsko** [comment]
You need add senderID in your .configure method. This resolved my problem. I'm use FCM.

**Comment by denizbas92** [comment]
@dattran97  Where should I add this configure part ?

**Comment by famu1hundred** [comment]
I have this correctly in the .configure method and I still receive this error. Any other places to look or indication as to what this error means and how to solve?

**Comment by bogrees** [comment]
Just figured this out, the example provided is slightly incorrect.  Essentially, in the constructor, it previously was only requiring two parameters; however, it needs a third (gcm id) to pass to the configure method within the constructor.  Since the gcm parameter is empty, you get the INVALID_PARAMETERS error.  The configure method only needs to be called once anyway, so I got it working by doing the following below.

Change the **constructor**() method in **NotifService.js** to this:
https://github.com/zo0r/react-native-push-notification/blob/master/example/NotifService.js
```
constructor() {
    this.lastId = 0;
  }
```

In App.js, change the call to the constructor to this:
```
this.notif = new NotifService();
```

And finally, call the **configure** method in **componentDidMount**:
```
this.notif.configure(this.onRegister.bind(this), this.onNotif.bind(this), "GCM_SENDER_ID");
```
