### ISSUE TITLE
Notification Channels

### ISSUE THREAD

**Issue by cidevant** [zo0r/react-native-push-notification#950]
How to properly use Notifications Channel? What is it? Why do we need this? You added new "variables" without explaining it. 

Should I do something with those channels? Should I create them? Does it really matter what I will write in `notification_channel_name` and `notification_channel_description`? 

Very bad documentation, very bad!

**Comment by itzpradip** [comment]
I'm also looking for this but nothing found yet. Is there anybody who can explain that, please?

**Comment by mmccartney** [comment]
The best documentation I've found explaining notification channels is this:
https://developer.android.com/training/notify-user/channels

From my reading of the code and issues in this project, we need to specify values as described in the [README.md](https://github.com/zo0r/react-native-push-notification#android-manual-installation).

That said, I believe the implementation only allows for a single channel (consistent with pre-channels Android).  I am not sure what needs to be fixed to make it so that it honors channels specified in the notification message itself.  If I can just get this to work with Firebase then maybe I'll get there :-)
