### ISSUE TITLE
onNotification is not being called when the app is inactive

### ISSUE THREAD

**Issue by Noor0** [zo0r/react-native-push-notification#972]
`react: 16.5.0`
`react-native: 0.57.1`
`react-native-push-notification: ^3.1.2`

i'm using this package for just local notifications, when the app is in foreground or background and a notification is tapped on, `onNotification` is called but when the app is killed/inactive and a notification is tapped it doesn't get called.

i've tried a couple of solutions from the issue threads but none worked,
i've added `android:launchMode="singleTask"` to my AndroidManifest.xml still.

i'm also using `react-native-splash-screen` could that be the reason for it as i noticed some issues mentioned that splash activity could be the cause of this.

**Comment by vinoa-team** [comment]
@Noor0 maybe you've checked already, but the config parameter `popInitialNotification` must be set to `true`

**Comment by jimerino** [comment]
Android has 2 kind of notifications: silent and noisy.

- The "noisy ones" only call onNotification when App is foreground but not in background
- The "silent ones" call onNotification even when App is in background

The only difference between them is that the silent ones only has the "data" section and doesn't have the "notification" section.

https://firebase.google.com/docs/cloud-messaging/concept-options

The solution I've made is modify the service to launch the 2 notifications. The silent one to trigger onNotif in every circumstances. The noisy one to show the notification in the notification center and make a sound.

But beware because if the app is in foreground, onNotification is called twice (for the silent and another for the noisy notification).

Regards

**Comment by JacobPoldenValtech** [comment]
@Noor0 did you ever get a fix for this? Same issue for me. OnNotification is called when app is in the foreground or completely dead. If its inactive, ie I am on WhatsApp but the app is open, the onNotification method isn't called and the app relaunches.

**Comment by Noor0** [comment]
Yeah, [check this issue](https://github.com/zo0r/react-native-push-notification/issues/727#issuecomment-386360518). I vaguely remember what I did but I think I registered my handler in the App.js and it worked, and to route user to different screen i took refs of the navigators and called routing functions on them [read this](https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html).

**Comment by Dallas62** [comment]
Hi,
This issue should be fixed on `3.3.1`.
