### ISSUE TITLE
Token not registering to device?

### ISSUE THREAD

**Issue by d-vincent** [zo0r/react-native-push-notification#991]
When sending test notifications through FCM, my device receives them if I target the entire application, but  I am not receiving anything when targeting the specific token I am receiving in onRegister (iOS only, Android is working fine)

Can anyone help?

I've followed every step for implementation, and remote notifications are receiving and showing as I want them except when I try to target a specific device.

**Comment by VicEsquivel** [comment]
Did you find what was the problem?

**Comment by d-vincent** [comment]
I did, my issue was that while the Android side was generating an FCM token, the iOS side was generating a GCM token. This was incredibly confusing and I'm not sure why it behaves this way, or what I could have done to properly generate an FCM token with this library. I ended up just grabbing the tokens from firebase itself.

**Comment by VicEsquivel** [comment]
@d-vincent Hmm, you mean grabbing the tokens directly from firebase console?

Because in my case I haven't managed to make the IOS version connect correctly to the firebase console to retrieve a valid FCM registration token...

I followed [this troubleshooting guide](https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html) which was pretty useful.

The token that the `onRegister` event from this library is returning, in my case is a 64 char length string, which turns to be the APNS token itself, that is why I successfully tested until point 4 in the guide, I could send a push notification to IOS using the [NWPusher](https://github.com/noodlewerk/NWPusher) that they mention, using this 64 length token.

While testing point 5 with a curl, I got the `InvalidRegistration ` error. So I deducted that maybe this library is never doing the firebase registration and that is why the token is not a FCM token at all.

After all it makes sense, this library has a little to none IOS native code, all the implementation in the readme is using react-native native's component [PushNotificationIOS](https://facebook.github.io/react-native/docs/pushnotificationios.html#content).

**Comment by d-vincent** [comment]
@VicEsquivel I use react-native-firebase, so I am able to call "firebase.messaging().getToken()" to grab the FCM token, and then use it in the same way I would use a token from onRegister

**Comment by Mavenic** [comment]
I am having the same problem, the token generated on ios is not a valid FCM token

**Comment by Anuj-Raghuvanshi** [comment]
Guys, Any solutions?

**Comment by anujraghuvanshi** [comment]
@messenja - As I mentioned above that I was having the same issue. This is because we need firebase token for push notification with firebase but this plugin generating APNS token for iOS. Hence it comes invalid for FCM. 

I used [This library](https://rnfirebase.io) and everything is working for me now. Meanwhile I am not sure on getting FCM token for iOS using this library. You can check if same problem is for you. If it is you can check for generating FCM token for iOS also.
