### ISSUE TITLE
Unable to get Device Token

### ISSUE THREAD

**Issue by Dhirajbhujbal** [zo0r/react-native-push-notification#998]
I am trying to use this lib. with the Salesforce SDK app in IOS device
When I am trying to create Local notification at that App is showing Push notification  but its configure method 'notification' is not getting called

Also on the launching of the application, When I ran 'onRegister ' it also not getting called to becasue of this I am unable get device token ID

**Comment by nimamyscreen** [comment]
having same issue in android

**Comment by simranaurora-evive** [comment]
I am also having the same issue

**Comment by timkuilman** [comment]
I have the same issue on iOS. As suggested elsewhere I added an event listener for registrationError to get more information.

`PushNotificationIOS.addEventListener('registrationError', (e) => console.log(error);`

In the iOS simulator it logs a message that onRegister is not supported in the simulator. That was expected. 

I am bugsnag to keep track of my errors in production but strange enough the event listener is not triggered in a testflight build. I am sure onRegister is not called in production since I store the token in the component's state and print it in the render function of App.js. 

- Entitlements are set in XCode (via capabilities)
- APNS is configured via the Apple Developer console


RN version is on 0.57.8

**Comment by timkuilman** [comment]
I have got it working on iOS! 

Not 100% sure what fixed it though. I think that the trick was to move PushNotifictions.configure({) from componentDidMount to the constructor! I can't give a logic explanation why it works now. 

Another important think: if your onRegister function is NOT an ES6 array function you can not access the this context of a class component. So in other words, if you try to call this.setState or this.props.someReduxActionCreator it will not work. 


```
class PushHandler extends React.Component {
  constructor(props) {
    super(props);

    PushNotification.configure({
      onRegister: token => {
        // Calling the redux action creator that was mapped to the props via mapDispatchToProps
        props.updateUserKey({ deviceToken: token });
        // Or store it in AsyncStorage, or in my case RNSecureStorage.
        RNSecureStorage.set('deviceToken', JSON.stringify(token), {
          accessible: ACCESSIBLE.WHEN_UNLOCKED
        });
      },
      onNotification: notification => {
        Alert.alert(JSON.stringify(notification));
      },
     ...

```

**Comment by pvanny1124** [comment]
@timkuilman does this work for iOS simulator?

**Comment by euharrison** [comment]
I had the same experience, my solution was uninstall the app and install again, maybe is something cached based on a different lib

**Comment by bossajie** [comment]
I need help, I still can't get the device token, there are no more errors at all, the onRegister is not returning the token at all. I am using external device IOS.

**Comment by EDGEFROST** [comment]
hi I am facing the same problem got any luck ??
